services:
  backend:
    command: sh -c "yarn start:dev"
    build: ./backend
    ports:
      - "4005:4005"
    volumes:
      - "./backend/src:/app/src"
    env_file:
      - ./db.env
      - ./.env
  db:
    image: postgres
    restart: always
    env_file:
      - ./db.env
    ports:
      - 5435:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d opportune -U utilisateur"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - wmdatabase:/var/lib/postgresql/data
    environment:
            WDS_SOCKET_PORT: 8080
  adminer:
    image: adminer
    restart: always
    ports:
      - 8088:8080
volumes:
  wmdatabase: